services:
  - type: worker
    name: zoya-agent
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: LIVEKIT_URL
        value: wss://support-agent-zpfvruon.livekit.cloud
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: CARTESIA_API_KEY
        sync: false
